<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdventOfCode.Commons\AdventOfCode.Commons.csproj" />
    <ProjectReference Include="..\src\AoC_2015\AdventOfCode.Year2015\AdventOfCode.Year2015.csproj" />
    <ProjectReference Include="..\src\AoC_2025\AdventOfCode.Year2025\AdventOfCode.Year2025.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AdventOfCodeGate">
      <HintPath>..\Commons\AdventOfCodeGate.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
